### ISSUE TITLE
[Bug] Console project not start & docs is need to update

### ISSUE THREAD

**Issue by yuluo-yx** [LinuxSuRen/api-testing#415]
*Description*:

Console is start. but no.

*Repro steps*:

1. `npm i` or `cnpm i`
2. `npm run dev`

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:

1. win 11
2. node 20.12.2 npm 9.8.1

*Logs*:
```
$ npm run dev

> atest-ui@v0.0.14 dev
> vite


  VITE v4.5.3  ready in 686 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error: The following dependencies are imported but could not be resolved:

  @element-plus/icons-vue (imported by D:/open_sources/apitesting/console/atest-ui/src/views/TestCase.vue?id=0)
  lodash (imported by D:/open_sources/apitesting/console/atest-ui/src/views/types.ts)

Are they installed?
    at file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:45779:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:45187:38
Failed to resolve import "@element-plus/icons-vue" from "src\App.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\SecretManager.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\StoreManager.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestingPanel.vue". Does the file exist?
22:01:16 [vite] Internal server error: Failed to resolve import "@element-plus/icons-vue" from "src\App.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/open_sources/apitesting/console/atest-ui/src/App.vue:7:7
  5  |    Location,
  6  |    Share
  7  |  } from "@element-plus/icons-vue";
     |          ^
  8  |  import { ref, watch } from "vue";
  9  |  import { API } from "./views/net";
      at formatError (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44062:46)
      at TransformContext.error (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44058:19)      
      at normalizeUrl (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41844:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41998:47
      at async Promise.all (index 1)
      at async TransformContext.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41914:13)
      at async Object.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44352:30)      
      at async loadAndTransform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:55026:29)      
      at async viteTransformMiddleware (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64430:32)
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestSuite.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestCase.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestingPanel.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\SecretManager.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\StoreManager.vue". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist? (x2)
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestCase.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestSuite.vue". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist? (x2)
X [ERROR] Could not resolve "codemirror"

    node_modules/.store/vue-codemirror@6.1.1/node_modules/vue-codemirror/dist/vue-codemirror.esm.js:7:172:
      7 │ ...,watch as a,onBeforeUnmount as i,h as c}from"vue";import{basicSetup as s}from"codemirror";import{EditorState as l,Compartment as f,StateEffect as d}from"@codemirror/...
        ╵                                                                                 ~~~~~~~~~~~~

  You can mark the path "codemirror" as external to exclude it from the bundle, which will remove
  this error.

22:01:17 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.store/vue-codemirror@6.1.1/node_modules/vue-codemirror/dist/vue-codemirror.esm.js:7:172: ERROR: Could not resolve "codemirror"
    at failureErrorWithLog (D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649:15)
    at D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1058:25
    at D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
22:01:17 [vite] Internal server error: Failed to resolve import "@element-plus/icons-vue" from "src\App.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/open_sources/apitesting/console/atest-ui/src/App.vue:7:7
  5  |    Location,
  6  |    Share
  7  |  } from "@element-plus/icons-vue";
     |          ^
  8  |  import { ref, watch } from "vue";
  9  |  import { API } from "./views/net";
      at formatError (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44062:46)
      at TransformContext.error (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44058:19)      
      at normalizeUrl (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41844:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41998:47
      at async Promise.all (index 1)
      at async TransformContext.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41914:13)
      at async Object.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44352:30)      
      at async loadAndTransform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:55026:29)      
      at async viteTransformMiddleware (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64430:32)
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestingPanel.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\SecretManager.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\StoreManager.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestCase.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestSuite.vue". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist? (x2)
      7 │ ...,watch as a,onBeforeUnmount as i,h as c}from"vue";import{basicSetup as s}from"codemirror";import{EditorState as l,Compartment as f,StateEffect as d}from"@codemirror/... 
        ╵                                                                                 ~~~~~~~~~~~~

  You can mark the path "codemirror" as external to exclude it from the bundle, which will remove
  this error.

22:01:18 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.store/vue-codemirror@6.1.1/node_modules/vue-codemirror/dist/vue-codemirror.esm.js:7:172: ERROR: Could not resolve "codemirror"
    at failureErrorWithLog (D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649:15)
    at D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1058:25
    at D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
22:05:34 [vite] Internal server error: Failed to resolve import "@element-plus/icons-vue" from "src\App.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/open_sources/apitesting/console/atest-ui/src/App.vue:7:7
  5  |    Location,
  6  |    Share
  7  |  } from "@element-plus/icons-vue";
     |          ^
  8  |  import { ref, watch } from "vue";
  9  |  import { API } from "./views/net";
      at formatError (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44062:46)
      at TransformContext.error (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44058:19)      
      at normalizeUrl (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41844:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41998:47
      at async Promise.all (index 1)
      at async TransformContext.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41914:13)
      at async Object.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44352:30)      
      at async loadAndTransform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:55026:29)      
      at async viteTransformMiddleware (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64430:32)
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestingPanel.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\SecretManager.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\StoreManager.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestCase.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestSuite.vue". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist? (x2)
22:05:35 [vite] Internal server error: Failed to resolve import "@element-plus/icons-vue" from "src\App.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/open_sources/apitesting/console/atest-ui/src/App.vue:7:7
  5  |    Location,
  6  |    Share
  7  |  } from "@element-plus/icons-vue";
     |          ^
  8  |  import { ref, watch } from "vue";
  9  |  import { API } from "./views/net";
      at formatError (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44062:46)
      at TransformContext.error (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44058:19)      
      at normalizeUrl (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41844:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41998:47
      at async Promise.all (index 1)
      at async TransformContext.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41914:13)
      at async Object.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44352:30)      
      at async loadAndTransform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:55026:29)      
      at async viteTransformMiddleware (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64430:32)
X [ERROR] Could not resolve "codemirror"

    node_modules/.store/vue-codemirror@6.1.1/node_modules/vue-codemirror/dist/vue-codemirror.esm.js:7:172:
      7 │ ...,watch as a,onBeforeUnmount as i,h as c}from"vue";import{basicSetup as s}from"codemirror";import{EditorState as l,Compartment as f,StateEffect as d}from"@codemirror/... 
        ╵                                                                                 ~~~~~~~~~~~~

  You can mark the path "codemirror" as external to exclude it from the bundle, which will remove
  this error.

Failed to resolve import "@element-plus/icons-vue" from "src\views\StoreManager.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\SecretManager.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestingPanel.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestSuite.vue". Does the file exist?
Failed to resolve import "@element-plus/icons-vue" from "src\views\TestCase.vue". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist?
Failed to resolve import "lodash" from "src\views\types.ts". Does the file exist? (x2)
22:05:35 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.store/vue-codemirror@6.1.1/node_modules/vue-codemirror/dist/vue-codemirror.esm.js:7:172: ERROR: Could not resolve "codemirror"
    at failureErrorWithLog (D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649:15)
    at D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1058:25
    at D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
22:05:35 [vite] Internal server error: Failed to resolve import "@element-plus/icons-vue" from "src\App.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/open_sources/apitesting/console/atest-ui/src/App.vue:7:7
  5  |    Location,
  6  |    Share
  7  |  } from "@element-plus/icons-vue";
     |          ^
  8  |  import { ref, watch } from "vue";
  9  |  import { API } from "./views/net";
      at formatError (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44062:46)
      at TransformContext.error (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44058:19)      
      at normalizeUrl (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41844:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41998:47
      at async Promise.all (index 1)
      at async TransformContext.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41914:13)
      at async Object.transform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44352:30)      
      at async loadAndTransform (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:55026:29)      
      at async viteTransformMiddleware (file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64430:32)
X [ERROR] Could not resolve "codemirror"

    node_modules/.store/vue-codemirror@6.1.1/node_modules/vue-codemirror/dist/vue-codemirror.esm.js:7:172:
      7 │ ...,watch as a,onBeforeUnmount as i,h as c}from"vue";import{basicSetup as s}from"codemirror";import{EditorState as l,Compartment as f,StateEffect as d}from"@codemirror/... 
        ╵                                                                                 ~~~~~~~~~~~~

  You can mark the path "codemirror" as external to exclude it from the bundle, which will remove
  this error.

22:05:36 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.store/vue-codemirror@6.1.1/node_modules/vue-codemirror/dist/vue-codemirror.esm.js:7:172: ERROR: Could not resolve "codemirror"
    at failureErrorWithLog (D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649:15)
    at D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1058:25
    at D:\open_sources\apitesting\console\atest-ui\node_modules\.store\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

> And I didn't do anything other than the above steps.

**Comment by yuluo-yx** [comment]
BTW:  `npm install -g cnpm ....`
This part I don't see what his role is under this heading, it should be located at the very beginning of the document
![image](https://github.com/LinuxSuRen/api-testing/assets/77964041/5cf39cb4-ea93-4d67-b6f1-0a221473941c)

**Comment by yuluo-yx** [comment]
```
Administrator@yuluo-laptop MINGW64 /d/open_sources/apitesting/console/atest-ui (0503-yuluo/work)
$ npm install -g vite@4.5.3

removed 2 packages, and changed 8 packages in 19s

3 packages are looking for funding
  run `npm fund` for details

Administrator@yuluo-laptop MINGW64 /d/open_sources/apitesting/console/atest-ui (0503-yuluo/work)
$ npm run dev

> atest-ui@v0.0.14 dev
> vite


  VITE v4.5.3  ready in 609 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error: The following dependencies are imported but could not be resolved:

  @element-plus/icons-vue (imported by D:/open_sources/apitesting/console/atest-ui/src/views/TestCase.vue?id=0)
  lodash (imported by D:/open_sources/apitesting/console/atest-ui/src/views/types.ts)

Are they installed?
    at file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:45779:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/open_sources/apitesting/console/atest-ui/node_modules/.store/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:45187:38
```

**Comment by DWJ-Squirtle** [comment]
It can be added manually
`pnpm add @element-plus/icons-vue js-yaml lodash`
or
`npm install @element-plus/icons-vue js-yaml lodash`
