### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#476]
The server cannot start. See also the error stack:

```shell
│ fatal error: concurrent map writes                                                                                                                                                            ││                                                                                                                                                                                               ││ goroutine 8 [running]:                                                                                                                                                                        ││ github.com/linuxsuren/api-testing/pkg/server.(*storeExtManager).Start.func1({0xc000044a20, 0x2f}, {0xc0000478a0, 0x1e})                                                                       ││     /workspace/pkg/server/store_ext_manager.go:76 +0x1f7                                                                                                                                      ││ created by github.com/linuxsuren/api-testing/pkg/server.(*storeExtManager).Start in goroutine 1                                                                                               ││     /workspace/pkg/server/store_ext_manager.go:73 +0x265                                                                                                                                      ││                                                                                                                                                                                               ││ goroutine 1 [chan send]:                                                                                                                                                                      ││ os/signal.signal_enable(0xfc1c00?)                                                                                                                                                            ││     /usr/local/go/src/runtime/sigqueue.go:223 +0x65                                                                                                                                           ││ os/signal.enableSignal(...)                                                                                                                                                                   ││     /usr/local/go/src/os/signal/signal_unix.go:49                                                                                                                                             ││ os/signal.Notify.func1(0x2)                                                                                                                                                                   ││     /usr/local/go/src/os/signal/signal.go:145 +0x65                                                                                                                                           ││ os/signal.Notify(0xc0000d5920, {0xc00039fb80, 0x4, 0x1?})                                                                                                                                     ││     /usr/local/go/src/os/signal/signal.go:165 +0x195                                                                                                                                          ││ github.com/linuxsuren/api-testing/cmd.(*serverOption).runE(0xc000040420, 0xc00034f208, {0x0?, 0x0?, 0x0?})                                                                                    ││     /workspace/cmd/server.go:243 +0x9e9                                                                                                                                                       ││ github.com/spf13/cobra.(*Command).execute(0xc00034f208, {0xc00004d990, 0x1, 0x1})                                                                                                             ││     /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca                                                                                                                           ││ github.com/spf13/cobra.(*Command).ExecuteC(0xc00034e608)                                                                                                                                      ││     /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff                                                                                                                          ││ github.com/spf13/cobra.(*Command).Execute(0x14b7128?)                                                                                                                                         ││     /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13                                                                                                                           ││ main.main()                                                                                                                                                                                   ││     /workspace/main.go:14 +0x71                                                                                                                                                               ││                                                                                                                                                                                               ││ goroutine 6 [select]:                                                                                                                                                                         ││ github.com/linuxsuren/api-testing/pkg/server.(*storeExtManager).processCollect.func1()                                                                                                        ││     /workspace/pkg/server/store_ext_manager.go:99 +0x76                                                                                                                                       ││ created by github.com/linuxsuren/api-testing/pkg/server.(*storeExtManager).processCollect in goroutine 1                                                                                      ││     /workspace/pkg/server/store_ext_manager.go:97 +0x4f
```

**Comment by aargeee** [comment]
hey @LinuxSuRen can you provide some reproduction steps. I'd like to give this issue a try.

**Comment by LinuxSuRen** [comment]
Thanks for your attention. Actually, I only meet this problem once in a very long time. A good way to reproduce it is by writing unit tests for it. You can easily to create many goroutines.

**Comment by aargeee** [comment]
@LinuxSuRen Sure, I'll have a look at it.
